# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bull_bear', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gamble',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Option',
            new_name='Outcome',
        ),
    ]
