# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bull_bear', '0002_auto_20161107_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcome',
            old_name='gamble',
            new_name='event',
        ),
    ]
