# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bull_bear', '0005_auto_20161107_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='likelihood',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
