# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bull_bear', '0008_auto_20161119_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='staked_reputation',
            new_name='earnable_reputation',
        ),
    ]
